### ISSUE TITLE
Questions about the sign of the coefficients

### ISSUE THREAD

**Issue by gokceneraslan** [maiermarco/DirichletReg#2]
Hi,

First I'd like to thank you for this method and the easy-to-use R package. Dirichlet GLM model is getting popular in our field which is single-cell genomics where we compare cell type compositions of different samples under different conditions. 

I was a bit puzzled by the results in my latest analysis, this is why I'm filing this issue here. In my dataset, there is a condition variable `dis` with a base category of `h` and the response is a composition of three cell types, represented here as m1, m2 and m3. 

Here is how the proportions looks like between 3 conditions:

![image](https://user-images.githubusercontent.com/1140359/86518578-6743de80-be00-11ea-993e-016db8fa40d8.png)

When I fit the model with common Dirichlet parameterization, surprisingly we see that the coefficient of m1 group under `disl` condition is negative:

![image](https://user-images.githubusercontent.com/1140359/86518671-0537a900-be01-11ea-9eb4-2f94b034f650.png)

It's a bit puzzling that all `dis` coefficients are negative in all 3 groups, however from the plot it looks like mean proportion of the `l` group (green) is higher than the base `h` condition (red). So intuitively I was expecting a positive coefficient for at least m1 between `h` and `l` conditions. I wonder if this is due to the increasing variance of the `l` group. In the common Dirichlet parameterization coefficients represent both mean and the precision jointly, so what happens here I guess is probably that precision goes down and mean goes up, but the final coefficient is dominated more by the precision, hence the negative sign. Is this explanation correct?

As a solution I can switch to the alternative parameterization where precision and mean are modeled separately. However, the caveat there is the necessity to choose a base category in the response, which is not preferred in my analysis because we typically report coefficients and p-values for all response categories. 

As a workaround, I was wondering if it makes sense to use the alternative parameterization in a one-vs-rest manner for each response category (which then becomes more like a Beta regression, I think) and interpret the coefficients and p-values of each category.

If I do this, I get more "intuitive" results where `disl` is increasing in the m1 group:

![image](https://user-images.githubusercontent.com/1140359/86518706-55167000-be01-11ea-9394-ad106368b6ba.png)

Here are the results of other response categories:

![image](https://user-images.githubusercontent.com/1140359/86518889-14b7f180-be03-11ea-9a81-d16deb37cd03.png)

![image](https://user-images.githubusercontent.com/1140359/86518898-28635800-be03-11ea-9478-31352d54d10b.png)

Reproducible notebook is here https://nbviewer.ipython.org/gist/gokceneraslan/fefe874a4d0b15fb76c3bedc9799842d.

Sorry this is more like a set of questions rather than an issue but I think it might help other people in my field with similar questions. Thanks in advance.

Gokcen.

**Comment by maiermarco** [comment]
Dear Gökçen,

thanks for using my package and the notebook with your data and code! :)

So, without knowing what `dis` and `chem` really mean, I started by having a look at your data and making ternary plots for every combination of `dis` and `chem` (I messed up the normalization so the data are more compressed in this plot but it’s still informative):

![ternary_chem-dis](https://user-images.githubusercontent.com/8507832/86753866-b8421580-c040-11ea-8598-1b848dfdd341.png)

Groups "h" and "l" of `dis` look quite similar between "v2" and "v3" (first two columns of plots) but in `dis`-group "nl" there is a huge discrepancy between "v2" and "v3":

![NL_v2-v3](https://user-images.githubusercontent.com/8507832/86753901-bf692380-c040-11ea-9cb0-7cadcbe4aafe.png)

It seems to me, there is an interaction between the predictors. I made a (hand-drawn) profile plot of the 6 combinations therefore, and the inverted V-shape of the "nl" data in "v2" clearly goes against the (blue) profile in "v3":

![compositions_interaction](https://user-images.githubusercontent.com/8507832/86753926-c42dd780-c040-11ea-8042-9fb7bc2eb8e6.png)

I tried estimating a model with an interaction (`chem * dis`) but there are seemingly too few observations (esp. in "v2"; also group "nl" in "v2" has zero variance) to get stable results with the necessary 18 parameters.

--------

Generally, negative coefficients in the common param. are a result of the log-link, since alpha parameters must be >0. A regression coef. of 0 is actually exp(0)=1 in terms of the Dirichlet-distr.’ alphas, so negative values mean that the resulting alpha will be between in (0, 1). If you have alpha-parameters below 1, they "push density" to the sides of the support, which is why "U" or "L"/"J"-shaped densities can occur. Here is a screenshot of a [paper](https://epub.wu.ac.at/4077/) illustrating this (first column):

![dirichlet-densities](https://user-images.githubusercontent.com/8507832/86753964-ca23b880-c040-11ea-99c6-023132a02431.png)

With regard to your mostly negative parameters: that could be due to low precision, because the Dirichlet distr.’s alpha-parameters which are being modeled in the common param. can be seen as proportions "scaled" by precision, so alpha = {.1, .3, .6} has the same expected value as alpha = {10, 30, 60} but the first has a precision of phi = 1 and the latter phi = 100.

--------

If you take a look at the raw residuals of the main-effects model, obs. 3 and 4 ("v2", "nl") are massive outliers compared to the rest:

```
> resid(DirichReg(y ~ chem + dis, df), type = "raw")
              m1            m2            m3
[...snip...]
3  -0.1591162054  0.5746213325 -0.4155051271
4  -0.1591162054  0.5746213325 -0.4155051271
[...snip...]
```
--------

I don’t think the alt. param. will help in this case, because there seems to be an association between `chem` and `dis` (esp. in "nl" between "v2" and "v3") that needs to be adressed in both models.

One way to possibly fix this: Is there any way to get more data (esp. of `chem` == "v2")?

Hope this helps for now.

Kind regards,
Marco
